services:
  selenium-hub:
    image: selenium/hub:4.8.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-network

  chrome-node:
    image: selenium/node-chrome:4.8.0
    container_name: downloadmusic-chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network
    expose:
      - "5900"

  downloader:
    build: .
    container_name: music-downloader
    environment:
      - SELENIUM_URL=http://selenium-hub:4444/wd/hub
      - DOWNLOAD_PATH=/target
    volumes:
      - /mnt/storage/media/music/:/target
      - ./screenshots:/app/screenshots
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge
