services:
  youtube-watcher:
    build:
      context: .
      args:
        YT_DLP_VERSION: ${YT_DLP_VERSION:-2025.03.31}
    container_name: youtube-playlist-watcher
    # Ejecutar como el usuario del host para evitar problemas de permisos en el volumen
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - PLAYLIST_URL=${PLAYLIST_URL}
      - DOWNLOAD_PATH=${DOWNLOAD_PATH:-/downloads}
      - OBSERVER_INTERVAL_MS=${OBSERVER_INTERVAL_MS:-60000}
      # - COOKIES_FILE=${COOKIES_FILE}
    volumes:
      - ${HOST_DOWNLOAD_PATH:-./downloads}:/downloads
    networks:
      - downloader-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "yt-dlp --version >/dev/null 2>&1 && ffmpeg -version >/dev/null 2>&1"]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  downloader-network:
    driver: bridge
