version: '3.8'

services:
  youtube-watcher:
    build: .
    container_name: youtube-playlist-watcher
    # Ejecutar como el usuario del host para evitar problemas de permisos en el volumen
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - PLAYLIST_URL=${PLAYLIST_URL}
      - DOWNLOAD_PATH=${DOWNLOAD_PATH:-/downloads}
      - OBSERVER_INTERVAL_MS=${OBSERVER_INTERVAL_MS:-60000}
    volumes:
      - ${HOST_DOWNLOAD_PATH:-./downloads}:/downloads
    networks:
      - downloader-network
    restart: unless-stopped

networks:
  downloader-network:
    driver: bridge
