name: CI

on:
  push:
    branches: [ main, master, "**/*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Lint (flake8)
        run: flake8 src tests --max-line-length=88

      - name: Format check (black)
        run: black --check src tests scripts

      - name: Run tests (pytest)
        env:
          PYTHONPATH: src
        run: pytest -q
